// This file is auto-generated by @hey-api/openapi-ts

import { client, type Options, formDataBodySerializer } from '@hey-api/client-fetch';
import type { PostApiAuthenticationLoginData, PostApiAuthenticationLoginError, PostApiAuthenticationLoginResponse, ApiCommentPostData, ApiCommentPostError, ApiCommentPostResponse, ApiCommentGetListData, ApiCommentGetListError, ApiCommentGetListResponse, ApiMemePostData, ApiMemePostError, ApiMemePostResponse, ApiMemeGetListData, ApiMemeGetListError, ApiMemeGetListResponse, GetApiMemesByMemeIdPictureData, GetApiMemesByMemeIdPictureError, GetApiMemesByMemeIdPictureResponse, GetApiUsersByUserIdData, GetApiUsersByUserIdError, GetApiUsersByUserIdResponse, ApiUserGetData, ApiUserGetError, ApiUserGetResponse } from './types.gen';

export const postApiAuthenticationLogin = (options?: Options<PostApiAuthenticationLoginData>) => { return (options?.client ?? client).post<PostApiAuthenticationLoginResponse, PostApiAuthenticationLoginError>({
    ...options,
    url: '/api/authentication/login'
}); };

export const apiCommentPost = (options: Options<ApiCommentPostData>) => { return (options?.client ?? client).post<ApiCommentPostResponse, ApiCommentPostError>({
    ...options,
    url: '/api/memes/{memeId}/comments'
}); };

export const apiCommentGetList = (options: Options<ApiCommentGetListData>) => { return (options?.client ?? client).get<ApiCommentGetListResponse, ApiCommentGetListError>({
    ...options,
    url: '/api/memes/{memeId}/comments'
}); };

export const apiMemePost = (options?: Options<ApiMemePostData>) => { return (options?.client ?? client).post<ApiMemePostResponse, ApiMemePostError>({
    ...options,
    ...formDataBodySerializer,
    url: '/api/memes'
}); };

export const apiMemeGetList = (options?: Options<ApiMemeGetListData>) => { return (options?.client ?? client).get<ApiMemeGetListResponse, ApiMemeGetListError>({
    ...options,
    url: '/api/memes'
}); };

export const getApiMemesByMemeIdPicture = (options: Options<GetApiMemesByMemeIdPictureData>) => { return (options?.client ?? client).get<GetApiMemesByMemeIdPictureResponse, GetApiMemesByMemeIdPictureError>({
    ...options,
    url: '/api/memes/{memeId}/picture'
}); };

export const getApiUsersByUserId = (options: Options<GetApiUsersByUserIdData>) => { return (options?.client ?? client).get<GetApiUsersByUserIdResponse, GetApiUsersByUserIdError>({
    ...options,
    url: '/api/users/{userId}'
}); };

export const apiUserGet = (options: Options<ApiUserGetData>) => { return (options?.client ?? client).get<ApiUserGetResponse, ApiUserGetError>({
    ...options,
    url: '/api/users'
}); };